## Basic Configuration

baseurl = "https://rabetian.net"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Eike Rabetian"
title = "Eike Rabetian"

theme = "hugo-goa"

## Hugo Built-in Features
## disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Eike Rabetian"
intro = "Python Consultant | Backend Engineer"
description = "Now @ShipUp. Previously @Ariana, @Parsian and @GiGaComputers. <br/> \"I help people make the world's best software.\""
authorimage = "headshot.jpg"
dateformat = "Oct 8, 2020"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "python,blog,software,engineer,developer"

## Social Accounts
[params.social]
github = "mohammadrabetian"
instagram = "mohammadrabetian"
linkedin = "mohammad-rabetian-324a57143"
twitter = "mrabetian"
##facebook = "<username>"
##google = "<username>"
stackoverflow = "13362409/tommy"
email = "mohammadrabetian@yahoo.com"

## Extras
[params.extra]
copyright = "© 2020. Eike Rabetian. All rights reserved." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
